"""
Load test for the ForensiX ZR Unit API.

Run against a running backend instance:
    locust -f load_tests/locustfile.py --host http://127.0.0.1:8000

Headless example (50 users, spawn 5/sec, 60 seconds):
    locust -f load_tests/locustfile.py --host http://127.0.0.1:8000 \
        --headless -u 50 -r 5 -t 60s --csv=load_tests/results

Two user classes are simulated:

- ReadHeavyOfficer: logs in once, then repeatedly hits the read-heavy
  endpoints (dashboard stats/trends, report/case listing) that real officers
  use throughout a shift. None of these are rate-limited, so this measures
  actual server/database throughput under concurrency.

- WritingCitizen: registers a fresh account and repeatedly submits reports.
  Report submission IS rate-limited (10/minute) and, like login/register,
  keyed by source IP — with every simulated user originating from the same
  test machine, this class is expected to start hitting 429s quickly. That
  is intentional: it demonstrates the real behavior of a shared-IP swarm
  (e.g. citizens behind the same NAT/mobile carrier) against the current
  per-IP rate limiting, which is worth knowing before it happens in
  production.
"""
import random
import uuid

from locust import HttpUser, task, between


ADMIN_OFFICER_CODE = "ZR-OFC-101"

REPORT_CATEGORIES = ["Theft", "Vandalism", "Traffic Incident", "Public Safety", "Fraud"]


# officer_code is unique per user (one code = one specific officer's badge),
# so simulated officers can't each register their own account with a shared
# code. Instead, all ReadHeavyOfficer instances share ONE pre-registered
# account and log in independently with those credentials, same as many
# browser tabs/shifts of the same officer would.
_SHARED_OFFICER_USERNAME = "loadtest_shared_officer"
_SHARED_OFFICER_PASSWORD = "loadtest_pass1"


class ReadHeavyOfficer(HttpUser):
    weight = 3
    wait_time = between(1, 3)

    def on_start(self):
        # Harmless if it already exists (409/400) — first user to run this wins.
        self.client.post("/api/auth/register", json={
            "full_name": "Load Test Officer",
            "username": _SHARED_OFFICER_USERNAME,
            "email": f"{_SHARED_OFFICER_USERNAME}@example.com",
            "password": _SHARED_OFFICER_PASSWORD,
            "role": "officer",
            "officer_code": ADMIN_OFFICER_CODE,
        }, name="/api/auth/register [officer, idempotent]")
        resp = self.client.post("/api/auth/login", json={
            "username": _SHARED_OFFICER_USERNAME,
            "password": _SHARED_OFFICER_PASSWORD,
            "role": "officer",
            "officer_code": ADMIN_OFFICER_CODE,
        })
        token = resp.json().get("access_token") if resp.status_code == 200 else None
        self.headers = {"Authorization": f"Bearer {token}"} if token else {}

    @task(3)
    def dashboard_stats(self):
        self.client.get("/api/dashboard/stats", headers=self.headers, name="/api/dashboard/stats")

    @task(2)
    def dashboard_trends(self):
        self.client.get("/api/dashboard/trends", headers=self.headers, name="/api/dashboard/trends")

    @task(2)
    def list_reports(self):
        self.client.get("/api/reports/", headers=self.headers, name="/api/reports/ [list]")

    @task(1)
    def list_cases(self):
        self.client.get("/api/cases/", headers=self.headers, name="/api/cases/ [list]")


class WritingCitizen(HttpUser):
    weight = 1
    wait_time = between(2, 5)

    def on_start(self):
        username = f"loadtest_citizen_{uuid.uuid4().hex[:10]}"
        password = "loadtest_pass1"
        self.client.post("/api/auth/register", json={
            "full_name": "Load Test Citizen",
            "username": username,
            "email": f"{username}@example.com",
            "password": password,
            "role": "citizen",
        })
        resp = self.client.post("/api/auth/login", json={
            "username": username,
            "password": password,
            "role": "citizen",
        })
        token = resp.json().get("access_token") if resp.status_code == 200 else None
        self.headers = {"Authorization": f"Bearer {token}"} if token else {}

    @task
    def submit_report(self):
        category = random.choice(REPORT_CATEGORIES)
        self.client.post("/api/reports/", headers=self.headers, name="/api/reports/ [create]", json={
            "title": f"{category} report",
            "category": category,
            "description": "Generated by load test.",
            "location": "Test Zone",
            "priority": "normal",
        })
