version: '3.8'

services:
  backend:
    build: ./forensix_backend_python
    container_name: forensix_backend
    ports:
      - "8000:8000"
    env_file:
      - ./forensix_backend_python/.env
    volumes:
      - uploads_data:/app/uploads
      - db_data:/app/forensix.db
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: forensix_frontend
    ports:
      - "5500:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  uploads_data:
  db_data:
