services:
  - type: web
    name: forensix-backend
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///./forensix.db
      - key: VALID_OFFICER_CODES
        value: ZR-ADMIN-001,ZR-OFC-101,ZR-OFC-102
      - key: CORS_ORIGINS
        value: "*"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SEED_DEMO_USERS
        value: "true"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
