# Synthetic training data for the report classifier.
# Each row: (description, category, priority)
# Categories match the options in frontend/unauthorized/report.html
REPORT_SAMPLES = [
    # Suspicious Activity
    ("A man has been loitering near the school gate for the past hour, looking into windows.", "Suspicious Activity", "high"),
    ("I noticed an unfamiliar car parked outside my neighbor's house for several days.", "Suspicious Activity", "normal"),
    ("Someone was taking photos of the bank entrance early this morning.", "Suspicious Activity", "normal"),
    ("A group of people were seen checking door handles of parked cars in the parking lot.", "Suspicious Activity", "high"),
    ("There is a stranger sitting in a van outside our street watching houses.", "Suspicious Activity", "normal"),
    ("I saw someone trying to peek through my neighbor's window last night.", "Suspicious Activity", "normal"),
    ("A person was seen wandering around the building rooftop without identification.", "Suspicious Activity", "normal"),
    ("Two men were seen marking houses with chalk symbols on our street.", "Suspicious Activity", "normal"),
    ("Someone left an unattended bag near the bus stop.", "Suspicious Activity", "high"),
    ("A suspicious drone was flying low over our residential area.", "Suspicious Activity", "normal"),

    # Robbery
    ("Armed men just robbed the grocery store at gunpoint and fled on a motorbike.", "Robbery", "urgent"),
    ("My shop was robbed an hour ago, the cashier was threatened with a knife.", "Robbery", "urgent"),
    ("Two robbers snatched my phone and wallet at gunpoint near the market.", "Robbery", "urgent"),
    ("A bank robbery is happening right now, robbers are inside with weapons.", "Robbery", "urgent"),
    ("I was robbed on my way home, they took my bag and ran away.", "Robbery", "high"),
    ("Armed robbers broke into our house last night and stole jewelry and cash.", "Robbery", "high"),
    ("Someone tried to rob the ATM booth but ran away when the alarm triggered.", "Robbery", "high"),
    ("A group of masked men robbed a jewelry shop and escaped in a car.", "Robbery", "urgent"),
    ("My motorcycle was snatched at knifepoint near the traffic signal.", "Robbery", "urgent"),
    ("A delivery rider was robbed of his bike and phone last evening.", "Robbery", "high"),

    # Theft
    ("Someone stole my bicycle from outside my house overnight.", "Theft", "normal"),
    ("My laptop bag was stolen from the office while I was at lunch.", "Theft", "normal"),
    ("A thief broke into my car and stole the stereo system.", "Theft", "normal"),
    ("My wallet was pickpocketed in the crowded market this afternoon.", "Theft", "normal"),
    ("Someone stole groceries from our doorstep delivery this morning.", "Theft", "normal"),
    ("My neighbor's motorcycle was stolen from the parking lot last night.", "Theft", "high"),
    ("Cash and documents were stolen from my office drawer.", "Theft", "normal"),
    ("A thief took my mobile phone from the table at the cafe.", "Theft", "normal"),
    ("Someone broke the lock and stole tools from our garage.", "Theft", "normal"),
    ("My bag with my passport and laptop was stolen from the bus.", "Theft", "high"),

    # Violence
    ("A fight broke out between two groups and people are getting badly hurt right now.", "Violence", "urgent"),
    ("A man is being beaten by a mob near the market, please send help immediately.", "Violence", "urgent"),
    ("Two neighbors got into a violent argument and one was injured with a stick.", "Violence", "high"),
    ("I witnessed a man attacking another person with a knife on the street.", "Violence", "urgent"),
    ("A bar fight turned violent and several people are injured.", "Violence", "urgent"),
    ("Someone punched my brother and broke his nose during an argument yesterday.", "Violence", "high"),
    ("A group of teenagers assaulted an elderly man at the bus stop.", "Violence", "high"),
    ("My coworker was physically attacked by another employee in the office.", "Violence", "high"),
    ("There was a violent clash between rival groups in our neighborhood last night.", "Violence", "urgent"),
    ("A man attacked a security guard with a rod outside the mall.", "Violence", "urgent"),

    # Harassment
    ("A man has been following me and making inappropriate comments every day on my way to work.", "Harassment", "high"),
    ("I keep receiving threatening and abusive messages from an unknown number.", "Harassment", "high"),
    ("A colleague keeps sending me unwanted messages despite being asked to stop.", "Harassment", "normal"),
    ("Someone has been harassing my sister outside her college gate.", "Harassment", "high"),
    ("I am being constantly harassed by my landlord over rent disputes.", "Harassment", "normal"),
    ("A stranger has been calling my house repeatedly and making rude remarks.", "Harassment", "normal"),
    ("My neighbor verbally harasses me every time I leave my house.", "Harassment", "normal"),
    ("A group of boys whistle and shout at girls passing by this street daily.", "Harassment", "normal"),
    ("I am receiving repeated unwanted calls from someone pretending to be a relative.", "Harassment", "normal"),
    ("Someone is spreading false rumors about me and harassing me online.", "Harassment", "normal"),

    # Missing Person
    ("My 8-year-old daughter has been missing since this morning, please help find her urgently.", "Missing Person", "urgent"),
    ("My elderly father with dementia has gone missing from the house.", "Missing Person", "urgent"),
    ("A teenager from our neighborhood has not returned home for two days.", "Missing Person", "high"),
    ("My friend has been missing since yesterday and is not answering calls.", "Missing Person", "high"),
    ("A young child was last seen playing near the park and is now missing.", "Missing Person", "urgent"),
    ("My brother left for work three days ago and never came back.", "Missing Person", "high"),
    ("An elderly woman wandered away from the care home and cannot be located.", "Missing Person", "urgent"),
    ("My cousin went out last night and has been unreachable since.", "Missing Person", "high"),
    ("A student did not return from school and parents are worried.", "Missing Person", "high"),
    ("My neighbor's son has been missing for several hours after school.", "Missing Person", "high"),

    # Cyber Crime
    ("My bank account was hacked and money was withdrawn without my permission.", "Cyber Crime", "urgent"),
    ("Someone created a fake social media profile using my photos.", "Cyber Crime", "normal"),
    ("I received a phishing email asking for my banking details.", "Cyber Crime", "normal"),
    ("My online shopping account was accessed and used to make unauthorized purchases.", "Cyber Crime", "high"),
    ("Someone is blackmailing me with private photos taken from my phone.", "Cyber Crime", "urgent"),
    ("My email account was hacked and used to send spam to my contacts.", "Cyber Crime", "normal"),
    ("I lost money after clicking a fraudulent link sent via SMS.", "Cyber Crime", "high"),
    ("Someone is impersonating me on social media to scam my friends.", "Cyber Crime", "high"),
    ("My computer was infected with ransomware demanding payment.", "Cyber Crime", "high"),
    ("An unknown person accessed my company email and leaked confidential files.", "Cyber Crime", "urgent"),

    # Drug Activity
    ("There is a group of people openly selling drugs near the playground.", "Drug Activity", "high"),
    ("I noticed suspicious drug dealing happening every night outside the building.", "Drug Activity", "high"),
    ("A house in our street is suspected of being used to manufacture drugs.", "Drug Activity", "high"),
    ("Teenagers are being approached by a dealer near the school.", "Drug Activity", "urgent"),
    ("I saw someone exchanging packets that looked like drugs in the alley.", "Drug Activity", "normal"),
    ("There is heavy drug use happening in the abandoned building nearby.", "Drug Activity", "normal"),
    ("A car repeatedly stops at night for what appears to be drug transactions.", "Drug Activity", "normal"),
    ("My neighbor is openly using and selling drugs from their apartment.", "Drug Activity", "high"),
    ("Suspicious packages are being delivered to a house known for drug activity.", "Drug Activity", "normal"),
    ("Young people are being lured into drug use at the local park.", "Drug Activity", "high"),

    # Domestic Abuse
    ("My neighbor is screaming for help, her husband is beating her right now.", "Domestic Abuse", "urgent"),
    ("I am being physically abused by my husband and need help immediately.", "Domestic Abuse", "urgent"),
    ("A woman next door is constantly being shouted at and hit by her partner.", "Domestic Abuse", "high"),
    ("My friend is trapped in an abusive relationship and is afraid to leave.", "Domestic Abuse", "high"),
    ("Children in the house next to us are being beaten by their father regularly.", "Domestic Abuse", "urgent"),
    ("I overheard violent arguments and crying from the apartment upstairs again.", "Domestic Abuse", "high"),
    ("My sister is being emotionally and physically abused by her husband.", "Domestic Abuse", "high"),
    ("Someone is locked inside a room and being abused by a family member.", "Domestic Abuse", "urgent"),
    ("An elderly person in our family is being mistreated by their caretaker.", "Domestic Abuse", "high"),
    ("My cousin's husband threatens her with violence whenever he is angry.", "Domestic Abuse", "high"),

    # Emergency
    ("There is a fire spreading rapidly in the building next to mine, please send help now.", "Emergency", "urgent"),
    ("Someone has collapsed on the street and is not breathing.", "Emergency", "urgent"),
    ("A gas leak is causing a strong smell and people are evacuating the building.", "Emergency", "urgent"),
    ("A car has crashed into a house and the driver is trapped inside.", "Emergency", "urgent"),
    ("There is a medical emergency, my father is having a heart attack.", "Emergency", "urgent"),
    ("A building is on fire and people are trapped on the upper floors.", "Emergency", "urgent"),
    ("A child has fallen into the canal and needs immediate rescue.", "Emergency", "urgent"),
    ("An explosion was heard near the market and there is smoke everywhere.", "Emergency", "urgent"),
    ("Someone is drowning in the river near the bridge, send help fast.", "Emergency", "urgent"),
    ("There is a severe accident on the highway with multiple injuries.", "Emergency", "urgent"),

    # Fraud
    ("I was scammed out of my savings by a fake investment company.", "Fraud", "high"),
    ("Someone sold me a fake property using forged documents.", "Fraud", "high"),
    ("I paid for an online order that was never delivered and the seller disappeared.", "Fraud", "normal"),
    ("A person collected donations claiming to be from a charity that doesn't exist.", "Fraud", "normal"),
    ("My identity was used to take out a loan without my knowledge.", "Fraud", "urgent"),
    ("I was tricked into transferring money for a fake job offer.", "Fraud", "high"),
    ("A contractor took advance payment for renovation work and never showed up.", "Fraud", "normal"),
    ("Someone forged my signature on a financial document.", "Fraud", "high"),
    ("I received counterfeit currency in change from a local shop.", "Fraud", "normal"),
    ("A fake lottery call asked me to pay a fee to claim a prize.", "Fraud", "normal"),

    # Vandalism
    ("Someone spray-painted graffiti all over the school walls overnight.", "Vandalism", "normal"),
    ("My car windows were smashed in the parking lot.", "Vandalism", "normal"),
    ("Vandals damaged the playground equipment in the park.", "Vandalism", "normal"),
    ("Street lights in our area have been deliberately broken by a group of youths.", "Vandalism", "normal"),
    ("Someone slashed the tires of several cars on our street.", "Vandalism", "normal"),
    ("The community center's windows were broken by vandals last night.", "Vandalism", "normal"),
    ("Public benches in the park have been destroyed by vandals.", "Vandalism", "normal"),
    ("Someone scratched and damaged the paint on my car deliberately.", "Vandalism", "normal"),
    ("Vandals broke into the school and damaged classroom furniture.", "Vandalism", "high"),
    ("Graffiti and broken fixtures were found in the public restroom this morning.", "Vandalism", "normal"),

    # Traffic Incident
    ("There was a major car accident at the main intersection with several vehicles involved.", "Traffic Incident", "high"),
    ("A motorcyclist was hit by a car and is lying injured on the road.", "Traffic Incident", "urgent"),
    ("Two cars collided at the roundabout causing a traffic jam.", "Traffic Incident", "normal"),
    ("A truck overturned on the highway blocking both lanes.", "Traffic Incident", "high"),
    ("A pedestrian was hit by a speeding car near the school crossing.", "Traffic Incident", "urgent"),
    ("There is reckless driving and racing happening on our street every night.", "Traffic Incident", "normal"),
    ("A bus and a car collided at the signal, minor injuries reported.", "Traffic Incident", "normal"),
    ("An accident occurred near the bridge causing a long traffic backup.", "Traffic Incident", "normal"),
    ("A cyclist was knocked down by a car that fled the scene.", "Traffic Incident", "high"),
    ("Cars are illegally parked blocking the ambulance route to the hospital.", "Traffic Incident", "normal"),

    # Public Safety
    ("A broken manhole cover on the main road is a serious hazard for pedestrians.", "Public Safety", "normal"),
    ("Streetlights in our entire neighborhood have not been working for weeks.", "Public Safety", "normal"),
    ("A large pothole on the highway is causing accidents.", "Public Safety", "high"),
    ("An abandoned construction site has no barriers and children play near it.", "Public Safety", "normal"),
    ("A dangerous loose electrical wire is hanging low over the footpath.", "Public Safety", "high"),
    ("Stray dogs have been aggressively chasing pedestrians in our area.", "Public Safety", "normal"),
    ("The footbridge near the station has a large hole and is unsafe to cross.", "Public Safety", "high"),
    ("A water tank on the roof of an old building looks like it could collapse.", "Public Safety", "high"),
    ("Garbage has been piling up for weeks creating a health hazard.", "Public Safety", "normal"),
    ("An unsecured construction crane is swaying dangerously in the wind.", "Public Safety", "high"),

    # Other
    ("I would like to report a general concern about noise pollution in our area.", "Other", "normal"),
    ("There has been a strong unpleasant smell coming from a nearby factory for days.", "Other", "normal"),
    ("I want to report illegal construction work happening without permits.", "Other", "normal"),
    ("Loud music from a nearby venue continues late into the night disturbing residents.", "Other", "normal"),
    ("I want to report a general complaint about poor maintenance of public property.", "Other", "normal"),
    ("There is an unregistered business operating without proper licensing nearby.", "Other", "normal"),
    ("I want to raise a concern about overcrowding at the local market.", "Other", "normal"),
    ("I have a general inquiry about community safety programs in our area.", "Other", "normal"),
    ("I want to report unauthorized vendors blocking the pedestrian pathway.", "Other", "normal"),
    ("This is a general feedback report about service quality at the local office.", "Other", "normal"),
]
